// list users
export const LIST_USERS = 'LIST_USERS';
export const LIST_USERS_IN_PROGRESS = 'LIST_USERS_IN_PROGRESS';
export const LIST_USERS_SUCCESS = 'LIST_USERS_SUCCESS';
export const LIST_USERS_FAILED = 'LIST_USERS_FAILED';

// add new user
export const ADD_USER = 'ADD_USER';
export const ADD_USER_IN_PROGRESS = 'ADD_USER_IN_PROGRESS';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';

// edit user
export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_IN_PROGRESS = 'EDIT_USER_IN_PROGRESS';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

// delete user
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_IN_PROGRESS = 'DELETE_USER_IN_PROGRESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export default {
    LIST_USERS,
    LIST_USERS_IN_PROGRESS,
    LIST_USERS_SUCCESS,
    LIST_USERS_FAILED,
    ADD_USER,
    ADD_USER_IN_PROGRESS,
    ADD_USER_SUCCESS,
    ADD_USER_FAILED,
    EDIT_USER,
    EDIT_USER_IN_PROGRESS,
    EDIT_USER_SUCCESS,
    EDIT_USER_FAILED,
    DELETE_USER,
    DELETE_USER_IN_PROGRESS,
    DELETE_USER_SUCCESS,
    DELETE_USER_FAILED
};
